### ISSUE TITLE
Docking issue with the model

### ISSUE THREAD

**Issue by rohityadav901** [aretasg/dockit#2]
Hi, 

I docked 100 ligands against one protein only but was facing issue, related to double docking of the ligands. 
For example i docked compound_1, compound_2, compound_3.. compund_100 with a protein named 4PLM. So compound_2 was docking two times in the whole process, same it happend with the other compounds. Kindy check this issue

**Comment by aretasg** [comment]
Hi,

Thank you for contacting. This is not an issue but a known behaviour. Before each new docking please make sure the PDBQT folders are empty to avoid duplicates. Upon initiation the bash script copies ligands to PDBQT folder and in your case creating duplicates which then are docked with Vina.
